package entity;

// Start of user code for imports
import java.util.*;
import org.minueto.image.MinuetoImage;
// End of user code

/**
 * Animation class definition.
 * Generated by the TouchCORE code generator.
 */
public abstract class Animation {
    
    protected int index;
    protected int delay;
    protected int timesPlayed;
    protected long timer;
    protected int speed;
    protected boolean playing;

	public abstract void update();

    public abstract MinuetoImage getCurrentFrame();
    
    public boolean isPlaying() {
		return playing;
	}

	public void play() {
		this.playing = true;
	}
	
	public void stop() {
		this.playing = false;
		this.timer = 0;
	}
	
	public boolean hasPlayed(int i) { 
		return timesPlayed == i; 
	}
}
