package entity;

// Start of user code for imports
import java.util.*;
// End of user code

import org.minueto.image.MinuetoImage;

/**
 * Armor class definition.
 * Generated by the TouchCORE code generator.
 */
public class Armor extends Item {

	protected int defence;
	
    public Armor(String n, String d, MinuetoImage i, int defence) {
		super(n, d, i);
		this.defence = defence;
		// TODO Auto-generated constructor stub
	}   
    public int getDefence() {
        return this.defence;
    }
}
