package entity;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * Entity class definition.
 * Generated by the TouchCORE code generator.
 */
public abstract class Entity {

	protected int width;
    protected int height;
    protected int positionX;
    protected int positionY;
    protected int destX;
    protected int destY;
    protected boolean moving;
    protected double moveSpeed;
    
    public abstract void update();

    public abstract Animation getAnimation();
    
    public int getPositionX() {
		return positionX;
	}

	public int getPositionY() {
		return positionY;
	}

	public void setPosition(int x, int y) {
		this.positionX = x;
		this.positionY = y;
		this.destX = this.positionX;
		this.destY = this.positionY;
	}

	public int getDestX() {
		return destX;
	}
	
	public int getDestY() {
		return destY;
	}
	
	public void setDest(int x, int y) {
		this.destX = x;
		this.destY = y;
	}

	public boolean isMoving() {
		return moving;
	}

	public void setMoving(boolean moving) {
		this.moving = moving;
	}

	public double getMoveSpeed() {
		return moveSpeed;
	}

	public void setMoveSpeed(double moveSpeed) {
		this.moveSpeed = moveSpeed;
	}
}
