package entity;

// Start of user code for imports
import java.util.*;
import org.minueto.image.MinuetoImage;
// End of user code

/**
 * Item class definition.
 * Generated by the TouchCORE code generator.
 */
public abstract class Item {
    
    protected String name;
    protected String description;
    protected MinuetoImage icon;
    
    public Item(String n, String d, MinuetoImage i){
    	this.name = n;
    	this.description = d;
    	this.setIcon(i);
    }
    
    MinuetoImage getIcon() {
        return this.icon;
    }

    boolean setIcon(MinuetoImage newObject) {
        this.icon = newObject;
        return true;
    }

    public String getName() {
        return this.name;
    }

    public String getDescription() {
        return this.description;
    }
}
