package entity;

// Start of user code for imports
import java.util.*;
import org.minueto.window.MinuetoWindow;
import map.LevelMap;
//End of user code

/**
 * UndirectedEntity class definition.
 * Generated by the TouchCORE code generator.
 */
public abstract class UndirectedEntity extends Entity {
    
    protected UndirectedAnimation animation;
    
	protected abstract void initiateAnimation();
	
    public UndirectedEntity(String name) {
    	super(name);
        initiateAnimation();
    }
    
    public UndirectedEntity(String name, int x, int y, LevelMap m) {
    	super(name, x, y, m);
        initiateAnimation();
    }
    
    public UndirectedEntity(String name, int x, int y, LevelMap m, int id) {
    	super(name, x, y, m);
    	this.id = id;
        initiateAnimation();
    }

    public UndirectedAnimation getAnimation() {
        return this.animation;
    }

    boolean setAnimation(UndirectedAnimation newObject) {
        this.animation = newObject;
        return true;
    }

    public void update() {
        if (this.animation != null) {
            animation.update();
        }
    }
}
