package entity;

// Start of user code for imports
import java.util.*;
// End of user code

import org.minueto.window.MinuetoWindow;

/**
 * UndirectedEntity class definition.
 * Generated by the TouchCORE code generator.
 */
public class UndirectedEntity extends Entity {
    
    protected UndirectedAnimation animation;
    
    public UndirectedEntity(UndirectedAnimation a) {
        this.animation = a;
        this.moving = false;
        this.moveSpeed = 4;
    }

    public UndirectedAnimation getAnimation() {
        return this.animation;
    }

    boolean setAnimation(UndirectedAnimation newObject) {
        this.animation = newObject;
        return true;
    }

    public void update() {
        if (this.animation != null) {
            animation.update();
        }
    }
}
