package entity;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * Weapon class definition.
 * Generated by the TouchCORE code generator.
 */
public class Weapon extends Item {
    
    protected int damage;
    protected int attackSpeed;
    
    public int getDamage() {
        return this.damage;
    }

    public int getAttackSpeed() {
        return this.attackSpeed;
    }
}
