package entity;

// Start of user code for imports
import java.util.*;
// End of user code

import org.minueto.image.MinuetoImage;

/**
 * Weapon class definition.
 * Generated by the TouchCORE code generator.
 */
 public class Weapon extends Item {
    
    protected int damage;
    protected int attackSpeed;
    
    /**
     * 
     * @param 60%attackSpeed = 0;
     */
    public Weapon(String n, String d, MinuetoImage i, int damage, int attackSpeed) {
    	super(n,d,i);
    	this.damage = damage;
    	this.attackSpeed = attackSpeed;
    }
    
    public int getDamage() {
        return this.damage;
    }

    public int getAttackSpeed() {
        return this.attackSpeed;
    }
}
