package woven_tilebasedgameengine;

// Start of user code for imports
import java.util.*;
import org.minueto.image.MinuetoImage;
// End of user code

/**
 * Animation class definition.
 * Generated by the TouchCORE code generator.
 */
public abstract class Animation {
    
    protected int index;
    protected int delay;
    protected int timesPlayed;
    protected long timer;
    protected int speed;
    protected long lastTime;
    
    public abstract void update();

    public abstract MinuetoImage getCurrentFrame();
}
