package woven_tilebasedgameengine;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * Armor class definition.
 * Generated by the TouchCORE code generator.
 */
public class Armor extends Item {
    
    protected int defence;
    
    public int getDefence() {
        return this.defence;
    }
}
