package woven_tilebasedgameengine;

// Start of user code for imports
import java.util.*;
import org.minueto.image.MinuetoImage;
import org.minueto.image.MinuetoText;
// End of user code

/**
 * CollectionOfAssociated class definition.
 * Generated by the TouchCORE code generator.
 */
abstract class CollectionOfAssociated {
    
    protected List<MinuetoImage> elements;
    protected List<MinuetoText> elements;
    protected List<Tile> elements;
    
    void add(int index, MinuetoImage a) {
        /* TODO: No message view defined */
    }

    MinuetoImage remove(int index) {
        /* TODO: No message view defined */
        return null;
    }

    MinuetoImage get(int index) {
        
    }

    boolean add(MinuetoImage a) {
        /* TODO: No message view defined */
        return false;
    }

    boolean remove(Object a) {
        
    }

    CollectionOfAssociated() {
        /* TODO: No message view defined */
    }

    boolean contains(Object o) {
        
    }

    int size() {
        
    }

    void add(int index, MinuetoText a) {
        /* TODO: No message view defined */
    }

    MinuetoText remove(int index) {
        /* TODO: No message view defined */
        return null;
    }

    MinuetoText get(int index) {
        
    }

    boolean add(MinuetoText a) {
        /* TODO: No message view defined */
        return false;
    }

    void add(int index, Tile a) {
        /* TODO: No message view defined */
    }

    Tile remove(int index) {
        /* TODO: No message view defined */
        return null;
    }

    Tile get(int index) {
        
    }

    boolean add(Tile a) {
        /* TODO: No message view defined */
        return false;
    }
}
