package woven_tilebasedgameengine;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * Entity class definition.
 * Generated by the TouchCORE code generator.
 */
abstract class Entity {
    
    protected int width;
    protected int height;
    protected int positionX;
    protected int positionY;
    protected int destX;
    protected int destY;
    protected boolean moving;
    protected double moveSpeed;
    
    public abstract void update();

    public abstract Animation getAnimation();
}
