package woven_tilebasedgameengine;

// Start of user code for imports
import java.util.*;
import org.minueto.handlers.MinuetoKeyboardHandler;
// End of user code

/**
 * KeyboardHandler class definition.
 * Generated by the TouchCORE code generator.
 */
abstract class KeyboardHandler implements MinuetoKeyboardHandler {
    
    void handleKeyPress(int arg0) {
        /* TODO: No message view defined */
    }

    void handleKeyRelease(int arg0) {
        /* TODO: No message view defined */
    }

    void handleKeyType(char arg0) {
        /* TODO: No message view defined */
    }
}
