package woven_tilebasedgameengine;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * Launcher class definition.
 * Generated by the TouchCORE code generator.
 */
public class Launcher {
    
    public static void main(String[] args) {
        Game game = new Game();
        game.startRenderLoop();
    }
}
