package woven_tilebasedgameengine;

// Start of user code for imports
import java.util.*;
import org.minueto.handlers.MinuetoMouseWheelHandler;
// End of user code

/**
 * MouseWheelHandler class definition.
 * Generated by the TouchCORE code generator.
 */
abstract class MouseWheelHandler implements MinuetoMouseWheelHandler {
    
    void handleMouseWheelRotate(int arg0) {
        /* TODO: No message view defined */
    }
}
