package woven_tilebasedgameengine;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * Object class definition.
 * Generated by the TouchCORE code generator.
 */
abstract class Object {
    
}
