package woven_tilebasedgameengine;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * Path class definition.
 * Generated by the TouchCORE code generator.
 */
public class Path {
    
    protected LinkedList<Tile> myTile;
    
    public Path() {
        /* TODO: No message view defined */
    }

    Tile getFirstMyTile() {
        Tile first = myTile.getFirst();
        return first;
    }

    Tile getLastMyTile() {
        Tile last = myTile.getLast();
        return last;
    }

    boolean addMyTileAt(int index, Tile a) {
        myTile.add(index, a);
        return true;
    }

    boolean removeMyTileAt(int index) {
        int size = myTile.size();
        if (size == minimum) {
            return false;
        }
        Tile removedElement = myTile.remove(index);
        boolean result = removedElement != null;
        return result;
    }

    Tile getMyTileAt(int index) {
        Tile associated = myTile.get(index);
        return associated;
    }

    boolean removeMyTile(Tile a) {
        int size = myTile.size();
        if (size == minimum) {
            return false;
        }
        boolean removed = myTile.remove(a);
        return removed;
    }

    boolean addMyTile(Tile a) {
        boolean added = myTile.add(a);
        return added;
    }

    Path() {
        LinkedList<Tile> collection = new LinkedList<Tile>();
    }

    boolean containsMyTile(Tile a) {
        boolean contains = myTile.contains(a);
        return contains;
    }

    int sizeOfMyTile() {
        int size = myTile.size();
        return size;
    }

    LinkedList<Tile> getMyTile() {
        return this.myTile;
    }
}
