package woven_tilebasedgameengine;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * RandomMapGenerator class definition.
 * Generated by the TouchCORE code generator.
 */
public class RandomMapGenerator {
    
    protected Random random;
    protected CollectionOfAssociated frontiers;
    
    Random getRandom() {
        return this.random;
    }

    boolean setRandom(Random newObject) {
        this.random = newObject;
        return true;
    }

    boolean addFrontiers(Tile a) {
        boolean contains = frontiers.contains(a);
        if (contains) {
            return false;
        }
        boolean added = frontiers.add(a);
        return added;
    }

    boolean addFrontiersAt(int index, Tile a) {
        boolean contains = frontiers.contains(a);
        if (contains) {
            return false;
        }
        frontiers.add(index, a);
        return true;
    }

    boolean removeFrontiersAt(int index) {
        Tile removedElement = frontiers.remove(index);
        boolean result = removedElement != null;
        return result;
    }

    Tile getFrontiersAt(int index) {
        Tile associated = frontiers.get(index);
        return associated;
    }

    boolean removeFrontiers(Tile a) {
        boolean removed = frontiers.remove(a);
        return removed;
    }

    RandomMapGenerator() {
        CollectionOfAssociated collection = new CollectionOfAssociated();
    }

    boolean containsFrontiers(Tile a) {
        boolean contains = frontiers.contains(a);
        return contains;
    }

    int sizeOfFrontiers() {
        int size = frontiers.size();
        return size;
    }

    CollectionOfAssociated getFrontiers() {
        return this.frontiers;
    }

    public boolean generate(int seed) {
        /* TODO: No message view defined */
        return false;
    }
}
