package woven_tilebasedgameengine;

// Start of user code for imports
import java.util.*;
import org.minueto.image.MinuetoImage;
// End of user code

/**
 * Tile class definition.
 * Generated by the TouchCORE code generator.
 */
public abstract class Tile {
    
    protected TileType type;
    protected boolean occupied;
    protected MinuetoImage sprite;
    protected Entity myEntity;
    
    MinuetoImage getSprite() {
        return this.sprite;
    }

    boolean setSprite(MinuetoImage newObject) {
        this.sprite = newObject;
        return true;
    }

    Entity getMyEntity() {
        return this.myEntity;
    }

    boolean setMyEntity(Entity newObject) {
        this.myEntity = newObject;
        return true;
    }

    public void update() {
        if (myEntity != null) {
            boolean checkOnEntity = checkOnEntity(this.myEntity);
            if (checkOnEntity) {
                this.myEntity = null;
            } else {
                myEntity.update();
            }
        }
    }

    private boolean checkOnEntity(Entity e) {
        return false;
    }
}
