package woven_tilebasedgameengine;

// Start of user code for imports
import java.util.*;
import org.minueto.handlers.MinuetoWindowHandler;
// End of user code

/**
 * WindowHandler class definition.
 * Generated by the TouchCORE code generator.
 */
abstract class WindowHandler implements MinuetoWindowHandler {
    
    void handleGetFocus() {
        /* TODO: No message view defined */
    }

    void handleLostFocus() {
        /* TODO: No message view defined */
    }

    void handleMinimizeWindow() {
        /* TODO: No message view defined */
    }

    void handleQuitRequest() {
        /* TODO: No message view defined */
    }

    void handleRestoreWindow() {
        /* TODO: No message view defined */
    }
}
