package scene;

// Start of user code for imports
import java.util.*;

import org.minueto.MinuetoColor;
import org.minueto.image.MinuetoFont;
import org.minueto.image.MinuetoImage;
import org.minueto.image.MinuetoText;
import org.minueto.window.MinuetoWindow;
// End of user code

import interactive.KeyboardHandler;
import interactive.Keys;

/**
 * PauseScene class definition.
 * Generated by the TouchCORE code generator.
 */
class PauseScene extends Scene {
    
    protected long tick;
    protected int currentOption;
    protected ArrayList<MinuetoImage> options;
    
    public PauseScene() {
        /* TODO: No message view defined */
    }

    boolean removeOptions(MinuetoImage a) {
        int size = options.size();
        if (size == 0) {
            return false;
        }
        boolean removed = options.remove(a);
        return removed;
    }

    boolean addOptionsAt(int index, MinuetoImage a) {
        options.add(index, a);
        return true;
    }

    boolean removeOptionsAt(int index) {
        int size = options.size();
        if (size == 0) {
            return false;
        }
        MinuetoImage removedElement = options.remove(index);
        boolean result = removedElement != null;
        return result;
    }

    MinuetoImage getOptionsAt(int index) {
        MinuetoImage associated = options.get(index);
        return associated;
    }

    boolean addOptions(MinuetoImage a) {
        boolean added = options.add(a);
        return added;
    }

    boolean containsOptions(MinuetoImage a) {
        boolean contains = options.contains(a);
        return contains;
    }

    int sizeOfOptions() {
        int size = options.size();
        return size;
    }


    public void update() {
        handleInput();
    }

    public void init() {
    	MinuetoFont fontPause = new MinuetoFont("Arial",60,false, false); 
		MinuetoText textPause = new MinuetoText("Pause", fontPause, MinuetoColor.WHITE,true);
		this.addOptions(textPause);
    }

    public void draw(MinuetoWindow w) {
    	MinuetoColor white = new MinuetoColor(0, 0, 0);
        w.clear(white);
        for (int i = 0; i < this.options.size(); i++) {
            w.draw(this.options.get(i), 0, (i-1)*20);
        }
    }

    public void handleInput() {
        SceneManager sM = SceneManager.getInstance();
        if (KeyboardHandler.isPressed(Keys.E)) {
            sM.setPaused(false);
        }
    }
}
