package scene;

// Start of user code for imports
import java.util.*;
import org.minueto.window.MinuetoWindow;
// End of user code

/**
 * Scene class definition.
 * Generated by the TouchCORE code generator.
 */
abstract class Scene {
    
    public abstract void update();

    public abstract void init();

    public abstract void draw(MinuetoWindow w);

    public abstract void handleInput();
}
