package interactive;

// Start of user code for imports
import java.util.*;
import org.minueto.handlers.MinuetoFocusHandler;
// End of user code

/**
 * FocusHandler class definition.
 * Generated by the TouchCORE code generator.
 */
abstract class FocusHandler implements MinuetoFocusHandler {
    
    void handleGetFocus() {
        /* TODO: No message view defined */
    }

    void handleLostFocus() {
        /* TODO: No message view defined */
    }
}
