package interactive;

/**
 * Keys enumeration definition.
 * Generated by the TouchCORE code generator.
 */
public enum Keys {
    UP,
    LEFT,
    DOWN,
    RIGHT,
    SPACE,
    ENTER,
    Q,
    E
}
