package interactive;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * MouseHandler class definition.
 * Generated by the TouchCORE code generator.
 */
public class MouseHandler {
    
    protected static double horiz;
    protected static double vertic;
    protected static boolean[] mouseState;
    protected static boolean[] prevMouseState;
    
    public MouseHandler() {
        MouseHandler.mouseState = new boolean[2];
        MouseHandler.prevMouseState = new boolean[2];
    }

    public void handleMouseMove(int arg0, int arg1) {
        MouseHandler.horiz = arg0;
        MouseHandler.vertic = arg1;
    }

    public void handleMousePress(int arg0, int arg1, int arg2) {
        if (arg2 == MinuetoMouse.MOUSE_BUTTON_LEFT) {
            mouseState[0] = true;
        } else if (arg2 == MinuetoMouse.MOUSE_BUTTON_RIGHT) {
            mouseState[1] = true;
        }
        MouseHandler.horiz = arg0;
        MouseHandler.vertic = arg1;
    }

    public void handleMouseRelease(int arg0, int arg1, int arg2) {
        if (arg2 == MinuetoMouse.MOUSE_BUTTON_LEFT) {
            mouseState[0] = false;
        } else if (arg2 == MinuetoMouse.MOUSE_BUTTON_RIGHT) {
            mouseState[1] = false;
        }
        MouseHandler.horiz = arg0;
        MouseHandler.vertic = arg1;
    }

    public static double getHoriz() {
        return horiz;
    }

    public static double getVertic() {
        return vertic;
    }

    public static void update() {
        prevMouseState[0] = mouseState[0];
        prevMouseState[1] = mouseState[1];
    }

    public static boolean isDown(int arg0) {
        return mouseState[arg0];
    }

    public static boolean isPressed(int arg0) {
        return mouseState[arg0] && !prevMouseState[arg0];
    }
}
