package interactive;

// Start of user code for imports
import java.util.*;
import org.minueto.handlers.MinuetoMouseHandler;
// End of user code

/**
 * MouseHandler class definition.
 * Generated by the TouchCORE code generator.
 */
abstract class MouseHandler implements MinuetoMouseHandler {
    
    void handleMouseMove(int arg0, int arg1) {
        /* TODO: No message view defined */
    }

    void handleMousePress(int arg0, int arg1, int arg2) {
        /* TODO: No message view defined */
    }

    void handleMouseRelease(int arg0, int arg1, int arg2) {
        /* TODO: No message view defined */
    }
}
